import Head from 'next/head'
import Navbar from './Navbar'

function Layout ({ children }) {
  return (
  <main>
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <Navbar />
    <section className="py-5 px-10 grid place-content-center">
      {children}
    </section>
  </main>
  )
}

export default Layout
